name: multimodal-across-domains-gaze-target-detection
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openh264=2.1.1
  - openssl=1.1.1q
  - pillow=8.4.0
  - pip=22.1.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.13
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - click==8.1.3
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - fonttools==4.34.4
    - gitdb==4.0.9
    - gitpython==3.1.27
    - imageio==2.16.0
    - joblib==1.1.0
    - kiwisolver==1.4.4
    - matplotlib==3.5.2
    - networkx==2.8.5
    - packaging==21.3
    - pandas==1.4.3
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.20.1
    - psutil==5.9.1
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - python-dotenv==0.20.0
    - pytz==2022.1
    - pywavelets==1.3.0
    - pyyaml==6.0
    - scikit-image==0.19.3
    - scikit-learn==1.1.2
    - scipy==1.9.0
    - sentry-sdk==1.9.3
    - setproctitle==1.3.1
    - shortuuid==1.0.9
    - smmap==5.0.0
    - threadpoolctl==3.1.0
    - tifffile==2022.8.8
    - timm==0.6.7
    - wandb==0.13.1
